// import './instance'
// import './lifecycle/index'
// import './data-binding/index'
// import './computed/index'
// import './directive/index'
// import './computed/define'
// import './component/extend.js'
import './computed/v-model'

// import './computed/features'
// import './computed/render'
